version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/changedetection-io"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/certmanager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/falco"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/my-nginx"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/argocd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/greptimedb-operator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/metrics-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/dependencytrack"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/kyverno"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/access-policies"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/grafana"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/krane"
    schedule:
      interval: "weekly"
