{{- if and .Values.createDB.enabled .Values.createDB.standaloneDB }}
apiVersion: greptime.io/v1alpha1
kind: GreptimeDBStandalone
metadata:
  name: {{ .Values.createDB.dbName }}
spec:
  base:
    main:
      image: greptime/greptimedb:latest
{{- end }}