apiVersion: v2
name: cert-manager
description: Umbrella chart - Cert Manager
type: application
version: 1.0.0

dependencies:
  - name: cert-manager
    version: 1.18.1
    repository: https://charts.jetstack.io
