apiVersion: v2
name: kyverno
description: Umbrella chart - Kyverno Server
type: application
version: 1.0.0

dependencies:
  - name: kyverno
    version: 3.4.4
    repository: https://kyverno.github.io/kyverno/
