name: Generate Dependabot Config

on:
  workflow_dispatch:

jobs:
  generate-dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate dependabot.yaml
        run: |
          {
            echo "version: 2"
            echo "updates:"
            echo "  - package-ecosystem: \"github-actions\""
            echo "    directory: \"/\""
            echo "    schedule:"
            echo "      interval: \"weekly\""
          } > .github/dependabot.yml

          find charts -type f -name "Chart.yaml" | while read -r chart_file; do
            chart_dir=$(dirname "$chart_file")
            {
              echo "  - package-ecosystem: \"helm\""
              echo "    directory: \"/$chart_dir\""
              echo "    schedule:"
              echo "      interval: \"weekly\""
            } >> .github/dependabot.yml
          done


      - name: Commit and push dependabot.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .github/dependabot.yml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate dependabot.yaml"
            git push
          fi
