apiVersion: v2
name: argo-cd
description: Umbrella chart - ArgoCD Server
type: application
version: 1.0.0

dependencies:
  - name: argo-cd
    version: 8.1.2
    repository: https://argoproj.github.io/argo-helm
