name: Helm Chart Linting

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0 # Specify the Helm version you want to use

    - name: Lint Helm Charts
      run: |
        # Add any Helm repositories here if needed
        # helm repo add <repo-name> <repo-url>

        # Lint all charts in the charts directory
        for chart in charts/*; do
          if [ -d "$chart" ]; then
            echo "Update dependencies $chart"
            helm dependency update "$chart"
            echo "Linting $chart"
            helm lint "$chart"
          fi
        done
